#plot4
library(data.table)
library(datasets)
data<-data.frame(read.table("household_power_consumption.txt",header=TRUE,sep=";",na.strings="?",stringsAsFactors=FALSE))
data$DT2<-as.POSIXct(paste(data$Date,data$Time), format="%d/%m/%Y %H:%M:%S)
data_clean <-subset(data,data$DT2>="2007-02-01"& data$DT2<="2007-02-02 23:59:00")
png(filename="plot4.png",pointsize=12)
par(mfrow=c(2,2))
plot(data_clean$DT2,data_clean$Global_active_power,type="l",ylab="Global Active Power (kilowatts)",xlab="")
plot(data_clean$DT2,data_clean$Voltage,type="l",ylab="Voltage",xlab="datetime")
plot(data_clean$DT2,data_clean$Sub_metering_1,type="l",ylab="Energy sub metering",xlab="")
lines(data_clean$DT2,data_clean$Sub_metering_2,col="blue")
lines(data_clean$DT2,data_clean$Sub_metering_3,col="red")
legend("topright", lty = 1, col = c("black","blue", "red"), legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot(data_clean$DT2,data_clean$Global_reactive_power,type="l",ylab="Global_reactive_power",xlab="datetime")
dev.off()
