#plot3
library(data.table)
library(datasets)
data<-data.frame(read.table("household_power_consumption.txt",header=TRUE,sep=";",na.strings="?",stringsAsFactors=FALSE))
data$DT2<-as.POSIXct(paste(data$Date,data$Time), format="%d/%m/%Y %H:%M:%S)
data_clean <-subset(data,data$DT2>="2007-02-01"& data$DT2<="2007-02-02 23:59:00")
png(filename="plot3.png",pointsize=12)
plot(data_clean$DT2,data_clean$Sub_metering_1,type="l",ylab="Energy sub metering",xlab="")
lines(data_clean$DT2,data_clean$Sub_metering_2,col="blue")
lines(data_clean$DT2,data_clean$Sub_metering_3,col="red")
legend("topright", lty = 1, col = c("black","blue", "red"), legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()
